---
# tasks file for nodejs

- name: import os specific setup
  include_tasks: "setup_{{ ansible_os_family }}.yml"

- name: install global npm packages
  npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: yes
    state: latest
  with_items: "{{ npm_packages }}"